### PR TITLE
Fix deleted user link

### LINKED ISSUE #104: The deleted user's placeholder username label shouldn't allow navigation
## Description

When a user has deleted their account after creating a issue, or commenting on one, their name is replaced with **[deleted]** label which still allows navigation to the deleted user's profile.

## Steps to reproduce

1. Open an issue.
2. Comment on it.
3. Delete your account.
4. Go back to that issue you created.

**Expected behavior**
The **[deleted]** label should not be clickable. Clicking on it leads to a page which shows 404. This should be prevented.

**Screenshots**
The deleted label is clickable in both of these instances:

**Issue opened by deleted user:**

Issue opened by deleted user

**Comment by a deleted user on a issue:**

Comments on issue

**Clicking on the label always leads to a 404 page (as expected):**
image

### PR DESCRIPTION
**Pull request by mucyildiz**
## RYSOLV

Fixes #104 

Username links for deleted users are non clickable. I added styling for Deleted Users to remove hovering effects and added checks for if user is deleted on IssueDetailBody and CommentCard.

### CODE REVIEW

File: app/components/Issues/Detail/IssueDetailBody.jsx [hunk 1]
```diff
@@ -79,7 +80,13 @@ const IssueDetailBody = ({
     <Fragment>
       <PostingInfoWrapper>
         <div>
-          Opened by <UsernameLink to={route}>{username}</UsernameLink> on&nbsp;
+          Opened by{' '}
```
Comment (annapo23) [inline app/components/Issues/Detail/IssueDetailBody.jsx:83]: What are your thoughts on just using one styled-component for this? Perhaps we can pass in a variable that would determine in `pointer-events` should be `none` or `inherit`.
```
const isUserDeleted = username === '[deleted]';
...

<div>
          Opened by <UsernameLink isUserDeleted={isUserDeleted} to={route}>{username}</UsernameLink> on&nbsp;
          {moment(date)
            .utc()
            .format('M/D/YYYY')}
 </div>
```

File: app/components/Issues/Detail/styledComponents.js [hunk 2]
```diff
@@ -312,3 +312,8 @@ export const UsernameLink = styled(Link)`
     color: ${hoverLinkColor};
   }
 `;
+
+export const DeletedName = styled.div`
```
Comment (annapo23) [inline app/components/Issues/Detail/styledComponents.js:316]: If we go with the above approach, we can removed this and adjust the styling of `UsernameLink` to the following:
```
export const UsernameLink = styled(({ isUserDeleted, ...restProps }) => (
  <Link {...restProps} />
))`
  display: inline;
  font-weight: bold;
  pointer-events: ${({ isUserDeleted}) => isUserDeleted ? 'none' : 'inherit'};

  &:hover {
    text-decoration: underline;
  }
`;
```

File: app/components/MarkdownRender/Comments/CommentCard.jsx [hunk 3]
```diff
@@ -31,7 +32,12 @@ const CommentCard = ({
       <CommentContainer>
         <CommentHeader>
           <span>
-            Posted by&nbsp;<UsernameLink to={route}>{username}</UsernameLink>
+            Posted by&nbsp;{' '}
```
Comment (annapo23) [inline app/components/MarkdownRender/Comments/CommentCard.jsx:35]: Same comment as above.

File: app/components/MarkdownRender/styledComponents.js [hunk 4]
```diff
@@ -197,3 +197,9 @@ export const UsernameLink = styled(Link)`
     text-decoration: underline;
   }
 `;
+
+export const DeletedName = styled(Link)`
```
Comment (annapo23) [inline app/components/MarkdownRender/styledComponents.js:201]: Same comment as above.

**Review by annapo23 — CHANGES_REQUESTED** [review]
Awesome work, and much thanks for contributing to Rysolv. I left a couple comments below. Let me know what your thoughts are and if you have any questions :)

File: app/components/Issues/Detail/IssueDetailBody.jsx (hunk 1 above)
Comment (mucyildiz) [reply app/components/Issues/Detail/IssueDetailBody.jsx:83]: Yeah I think that's way better, I didn't know pointer-events was a thing! Thank you, and I'll be sure to do that right away.

**Comment by mucyildiz** [comment]
> Awesome work, and much thanks for contributing to Rysolv. I left a couple comments below. Let me know what your thoughts are and if you have any questions :)

Thank you for the feedback! I've just committed the changes

File: app/components/Issues/Detail/styledComponents.js [hunk 5]
```diff
@@ -304,11 +304,15 @@ export const TopBarWrapper = styled.div`
   height: 10rem;
 `;
 
-export const UsernameLink = styled(Link)`
+export const UsernameLink = styled(({ isUserDeleted, ...restProps }) => (
+  <Link {...restProps} />
+))`
   display: inline;
   font-weight: bold;
+  pointer-events: ${({ isUserDeleted }) =>
```
Comment (annapo23) [inline app/components/Issues/Detail/styledComponents.js:312]: Let's just have this be on one line so it's easier to read.

File: app/components/MarkdownRender/styledComponents.js [hunk 6]
```diff
@@ -189,9 +190,13 @@ export const UsernameExternalLink = styled.a`
   }
 `;
 
-export const UsernameLink = styled(Link)`
+export const UsernameLink = styled(({ isUserDeleted, ...restProps }) => (
+  <Link {...restProps} />
+))`
   display: inline;
   font-weight: bold;
+  pointer-events: ${({ isUserDeleted }) =>
```
Comment (annapo23) [inline app/components/MarkdownRender/styledComponents.js:198]: Let's just have this on one line.

**Review by annapo23 — CHANGES_REQUESTED** [review]
Perfect 💯 Thanks so much for making those changes. Two more very minor comments, and then it'll be good to merge in.

**Comment by mucyildiz** [comment]
> Perfect 💯 Thanks so much for making those changes. Two more very minor comments, and then it'll be good to merge in.

Done! Thanks for your help :)

**Review by annapo23 — COMMENTED** [review]
No, thank YOU! Would you mind pushing the code again, it seems like it didn't go through for some reason? 
Screen Shot 2021-07-14 at 3 35 49 PM

**Comment by mucyildiz** [comment]
@annapo23  I think it didn't change because Prettier is telling me we should have that on a new line and so when I push the branch it goes through a linter which fixes that and then pushes it. Do you think I should disable Prettier for that line?

**Review by annapo23 — APPROVED** [review]
No worries at all. It's nothing major, so I'll just go ahead and merge it in. Awesome job though - thanks so much for you help on this 🥇
