### PR TITLE
Filtering deleted users from attempting and watching list for issues

### LINKED ISSUE #88: Filter out deleted users in the attempting/watching count
## Description

We should filter out deleted users from the attempt / watch list

## Steps to reproduce

- Create a user account
- Start attempting/watching a few issues
- Delete your account
- Check the attempt / watch list

## Fix

~~Filter for the users `is_deleted` flag in the following files:~~
~~- https://github.com/rysolv/rysolv/blob/master/server/db/queries/issues/getIssueAttemptList.js~~
~~- https://github.com/rysolv/rysolv/blob/master/server/db/queries/issues/getIssues.js~~
~~- https://github.com/rysolv/rysolv/blob/master/server/db/queries/issues/getOneIssue.js~~
~~- Check the `issueCardValues` in ./constants for `getIssues.js` and `getOneIssue.js`~~

- In the delete user function, also remove the attempting & watching rows
  - https://github.com/rysolv/rysolv/blob/master/server/graphql/resolvers/users/deleteUser.js
- Create two new functions in db/queries/attempting & db/queries/watching
  - `removeAttempting` / `removeWatching`

## Claim this issue on rysolv
https://rysolv.com/issues/detail/f81fd17d-4ef8-421d-90cd-da3281ddfe16

### PR DESCRIPTION
**Pull request by ZeeshanZulfiqarAli**
Closes #88 

@annapo23  please review

### CODE REVIEW

**Review by tylermaran — CHANGES_REQUESTED** [review]
Update per comments in #88 

Your solution here would have worked. But I think that removing the rows at account deletion is the cleaner alternative.

File: server/db/queries/watching/removeWatching.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+const { singleQuery } = require('../../baseQueries');
+
+const removeWatching = async ({ userId }) => {
+  // Remove issueId and userId from attempting
```
Comment (tylermaran) [inline server/db/queries/watching/removeWatching.js:4]: incorrect comment

File: server/db/queries/attempting/removeAttempting.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
+const { singleQuery } = require('../../baseQueries');
+
+const removeAttempting = async ({ userId }) => {
+  // Remove issueId and userId from attempting
+  const deleteIssueQuery = `
+      DELETE FROM attempting
+      WHERE user_id = $1`;
+
+  await singleQuery({
+    queryText: deleteIssueQuery,
```
Comment (tylermaran) [inline server/db/queries/attempting/removeAttempting.js:10]: `deleteAttemptingQuery` would be a better name

File: server/db/queries/watching/removeWatching.js (hunk 1 above)
Comment (tylermaran) [reply server/db/queries/watching/removeWatching.js:4]: Also lets name this `deleteWatchingQuery`

File: server/graphql/resolvers/users/deleteUser.js [hunk 3]
```diff
@@ -12,6 +12,8 @@ const {
   deleteUserPullRequests,
   getUserSettings,
   transformUser,
+  removeWatching,
+  removeAttempting,
```
Comment (tylermaran) [inline server/graphql/resolvers/users/deleteUser.js:16]: alpha

File: server/db/index.js [hunk 4]
```diff
@@ -3,7 +3,7 @@ const {
   getRepoActivity,
   getUserActivity,
 } = require('./queries/activity');
-const { toggleAttempting } = require('./queries/attempting');
+const { toggleAttempting, removeAttempting } = require('./queries/attempting');
```
Comment (tylermaran) [inline server/db/index.js:6]: alpha

File: server/db/index.js [hunk 5]
```diff
@@ -73,7 +73,7 @@ const {
   searchUsers,
   transformUser,
 } = require('./queries/users');
-const { toggleWatching } = require('./queries/watching');
+const { toggleWatching, removeWatching } = require('./queries/watching');
```
Comment (tylermaran) [inline server/db/index.js:76]: alpha

**Review by tylermaran — CHANGES_REQUESTED** [review]

**Review by tylermaran — APPROVED** [review]
